config/routes.rb
Rails.application.routes.draw do
  resources :forum_categories
  resources :forum_posts
  resources :forum_threads

  devise_for :users
  resources :users

  get '/dashboard', to: 'users#dashboard'
  get '/forums', to: 'forum#index'
  get '/forums/:category', to: 'forum#category'
  get '/forums/:category/new', to: 'forum#new'
  get '/forums/:category/:thread', to: 'forum#thread'
  get '/forums/:category/:thread/reply', to: 'forum#reply'

  root to: "home#index"
end

app/models/forum_category.rb
class ForumCategory < ActiveRecord::Base
  has_many :forum_posts
end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
  belongs_to :forum_category
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :forum_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for( resource )
    return '/dashboard'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for( :sign_up ) << :username
    devise_parameter_sanitizer.for( :sign_in ) { |u| u.permit(:username, :email) }
  end
end

app/controllers/forum_categories_controller.rb
class ForumCategoriesController < ApplicationController
  before_action :set_forum_category, only: [:show, :edit, :update, :destroy]

  # GET /forum_categories
  # GET /forum_categories.json
  def index
    @forum_categories = ForumCategory.all
  end

  # GET /forum_categories/1
  # GET /forum_categories/1.json
  def show
  end

  # GET /forum_categories/new
  def new
    @forum_category = ForumCategory.new
  end

  # GET /forum_categories/1/edit
  def edit
  end

  # POST /forum_categories
  # POST /forum_categories.json
  def create
    @forum_category = ForumCategory.new(forum_category_params)

    respond_to do |format|
      if @forum_category.save
        format.html { redirect_to @forum_category, notice: 'Forum category was successfully created.' }
        format.json { render :show, status: :created, location: @forum_category }
      else
        format.html { render :new }
        format.json { render json: @forum_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_categories/1
  # PATCH/PUT /forum_categories/1.json
  def update
    respond_to do |format|
      if @forum_category.update(forum_category_params)
        format.html { redirect_to @forum_category, notice: 'Forum category was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_category }
      else
        format.html { render :edit }
        format.json { render json: @forum_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_categories/1
  # DELETE /forum_categories/1.json
  def destroy
    @forum_category.destroy
    respond_to do |format|
      format.html { redirect_to forum_categories_url, notice: 'Forum category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_category
      @forum_category = ForumCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_category_params
      params[:forum_category].permit(:name, :description)
    end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = ForumCategory.all
  end

  def thread
    @posts = ForumPost.where( thread_id: params[ :thread ] )
    @thread = ForumPost.find( params[ :thread ] )
    @category = ForumCategory.find( @thread.category_id )
  end

  def category
    @threads = ForumPost.where( 'category_id = ? AND original_post = ?', params[ :category ], true )
    @category = ForumCategory.find( params[ :category ] )
  end

  def new
    @category = ForumCategory.find( params[ :category ] )
    @forum_post = ForumPost.new
    @forum_post.user_id = current_user.id
    @forum_post.category_id = params[ :category ]
    @forum_post.original_post = true
    render 'forum_posts/new'
  end

  def reply
    @category = ForumCategory.find( params[ :category ] )
    @forum_post = ForumPost.new
    @forum_post.user_id = current_user.id
    @forum_post.category_id = params[ :category ]
    @forum_post.original_post = false
    @forum_post.thread_id = params[ :thread ]
    render 'forum_posts/new'
  end
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :set_forum_post, only: [:show, :edit, :update, :destroy]

  # GET /forum_posts/1/edit
  def edit
  end

  # POST /forum_posts
  # POST /forum_posts.json
  def create
    @forum_post = ForumPost.new( forum_post_params )
    @forum_post.user = current_user

    respond_to do |format|
      if @forum_post.save
        if @forum_post.original_post
          @forum_post.thread_id = @forum_post.id
          @forum_post.save
        end
        format.html { redirect_to "/forums/#{@forum_post.category_id}/#{@forum_post.thread_id}", notice: 'Forum post was successfully created.' }
        format.json { render :show, status: :created, location: @forum_post }
      else
        format.html { render :new }
        format.json { render json: @forum_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_posts/1
  # PATCH/PUT /forum_posts/1.json
  def update
    respond_to do |format|
      if @forum_post.update(forum_post_params)
        format.html { redirect_to "/forums/#{@forum_post.category_id}/#{@forum_post.thread_id}", thread: @forum_post.thread_id, notice: 'Forum post was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_post }
      else
        format.html { render :edit }
        format.json { render json: @forum_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_posts/1
  # DELETE /forum_posts/1.json
  def destroy
    @forum_post.destroy
    respond_to do |format|
      format.html { redirect_to forum_posts_url, notice: 'Forum post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_post
      @forum_post = ForumPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_post_params
      params.require(:forum_post).permit(:title, :author_id, :thread_id, :body, :category_id, :original_post)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def dashboard

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_categories_helper.rb
module ForumCategoriesHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forum/category.html.erb
<h1><%= @category.name %></h1>

<p><%= @category.description %></p>

<table>
  <thead>
    <tr><th>Title</th><th>Original Author</th><th>Last Commenter</th></tr>
  </thead>
  <tbody>
    <% @threads.each do |thread| %>
      <tr><td><%= link_to thread.title, "/forums/#{@category.id}/#{thread.id}" %></td><td><%= thread.user.username %></td><td></td></tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create Thread', "/forums/#{@category.id}/new" %>

app/views/forum/index.html.erb
<h1>Forums</h1>
<table>
  <thead>
    <tr><th>Category</th><th>Threads</th><th>Posts</th><th>Last Post</th></tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><h2><%= link_to category.name, "/forums/#{category.id}" %></h2><p><%= category.description %></p></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
</tbody>

app/views/forum/thread.html.erb
<table>
  <tbody>
    <% @posts.each do |post| %>
      <tr><td><%= post.user.username %></td><td><%= post.title %></td><td><%= post.body %></td><td></td></tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Reply', "/forums/#{@category.id}/#{@thread.id}/reply" %>

app/views/forum_categories/_form.html.erb
<%= form_for(@forum_category) do |f| %>
  <% if @forum_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_category.errors.count, "error") %> prohibited this forum_category from being saved:</h2>

      <ul>
      <% @forum_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_categories/edit.html.erb
<h1>Editing Forum Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_category %> |
<%= link_to 'Back', forum_categories_path %>

app/views/forum_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_categories.each do |forum_category| %>
      <tr>
        <td><%= forum_category.name %></td>
        <td><%= link_to 'Show', forum_category %></td>
        <td><%= link_to 'Edit', edit_forum_category_path(forum_category) %></td>
        <td><%= link_to 'Destroy', forum_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum category', new_forum_category_path %>

app/views/forum_categories/new.html.erb
<h1>New Forum Category</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_categories_path %>

app/views/forum_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_forum_category_path(@forum_category) %> |
<%= link_to 'Back', forum_categories_path %>

app/views/forum_posts/_form.html.erb
<%= form_for(@forum_post) do |f| %>
  <% if @forum_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_post.errors.count, "error") %> prohibited this forum_post from being saved:</h2>

      <ul>
      <% @forum_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <%= hidden_field( :forum_post, :user_id ) %>
  <%= hidden_field( :forum_post, :thread_id ) %>
  <%= hidden_field( :forum_post, :category_id ) %>
  <%= hidden_field( :forum_post, :original_post ) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_posts/edit.html.erb
<h1>Editing Forum Post</h1>

<%= render 'forum_posts/form' %>

<%= link_to 'Show', @forum_post %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Thread</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_posts.each do |forum_post| %>
      <tr>
        <td><%= forum_post.title %></td>
        <td><%= forum_post.user_id %></td>
        <td><%= forum_post.thread_id %></td>
        <td><%= forum_post.body %></td>
        <td><%= link_to 'Show', forum_post %></td>
        <td><%= link_to 'Edit', edit_forum_post_path(forum_post) %></td>
        <td><%= link_to 'Destroy', forum_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forum post', new_forum_post_path %>

app/views/forum_posts/new.html.erb
<h1>New Post in <%= @category.name %></h1>

<%= render 'forum_posts/form' %>

app/views/forum_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @forum_post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @forum_post.user.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @forum_post.body %>
</p>

<%= link_to 'Edit', edit_forum_post_path(@forum_post) %> |
<%= link_to 'Back', forum_posts_path %>

app/views/home/index.html.erb
<h1>Home Page</h1>
<p>This is the home page.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "The Lantern Watch" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><li><%= link_to "The Lantern Watch", root_path %></li></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="left">
      <% if user_signed_in? %>
        <li><%= link_to 'Forums', '/forums' %></li>
      <% end %>
    </ul>
  </section>
  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
      <% if user_signed_in? %>
        <li><%= link_to 'Users', users_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/users/dashboard.html.erb
<h1>Welcome, <%= current_user.username %>!</h1>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <tr><th>Username</th><th>Email</th></tr>
  <% @users.each do |user| %>
    <tr><td><%= user.username %></td><td><%= user.email %></td></tr>
  <% end %>
</table>